In [1]:
import tensorflow as tf

In [2]:
x = tf.ones((2, 2))
x

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[1., 1.],
       [1., 1.]], dtype=float32)>

In [3]:
with tf.GradientTape() as t:
    t.watch(x)
    y = tf.reduce_sum(x)
    z = tf.multiply(y, y)

dz_dx = t.gradient(z, x)
for i in [0, 1]:
    for j in [0, 1]:
        assert dz_dx[i][j].numpy() == 8.0

In [4]:
dz_dx

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[8., 8.],
       [8., 8.]], dtype=float32)>

In [5]:
y

<tf.Tensor: shape=(), dtype=float32, numpy=4.0>

In [6]:
z

<tf.Tensor: shape=(), dtype=float32, numpy=16.0>