In [1]:
import tensorflow as tf 

In [2]:
x = tf.zeros([10, 10])
x += 2
x

<tf.Tensor: shape=(10, 10), dtype=float32, numpy=
array([[2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.]], dtype=float32)>

In [3]:
v = tf.Variable(1.0)
assert v.numpy() == 1.0

In [4]:
v

<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=1.0>

In [5]:
v.assign(3.0)

<tf.Variable 'UnreadVariable' shape=() dtype=float32, numpy=3.0>

In [6]:
v

<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=3.0>

In [7]:
v.assign(tf.square(v))

<tf.Variable 'UnreadVariable' shape=() dtype=float32, numpy=9.0>

In [8]:
v

<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=9.0>

In [9]:
class Model(object):
    def __init__(self):
        self.W = tf.Variable(5.0)
        self.b = tf.Variable(0.0)
    def __call__(self, x):
        return  self.W * x + self.b

In [10]:
model = Model()

In [11]:
model(3.0).numpy()

15.0

In [12]:
def loss(predicted_y, desired_y):
    return tf.reduce_mean(tf.square(predicted_y - desired_y))

In [13]:
TRUE_W = 3.0
TRUE_B = 2.0
NUM_EXAMPLES = 1000

inputs = tf.random.normal(shape=[NUM_EXAMPLES])
noise = tf.random.normal(shape=[NUM_EXAMPLES])

outputs = inputs * TRUE_W + TRUE_B + noise

In [14]:
outputs

<tf.Tensor: shape=(1000,), dtype=float32, numpy=
array([ 5.72838497e+00,  5.33012247e+00, -6.33286595e-01, -1.45033255e-01,
       -2.58234072e+00,  9.82701492e+00,  2.20729876e+00, -9.88010764e-01,
        7.47571373e+00,  4.89688683e+00,  2.76053286e+00,  4.84977150e+00,
       -1.63773581e-01, -3.19147646e-01, -5.60216331e+00,  2.20372200e+00,
        2.98684335e+00, -1.60546970e+00,  4.74295282e+00,  2.41095638e+00,
       -1.82223916e-01,  3.99718738e+00,  6.88936710e+00,  2.87586236e+00,
        2.56074691e+00,  4.20295763e+00,  7.09667444e+00,  1.70174146e+00,
        2.80214739e+00,  7.39377022e+00,  5.13045788e+00, -7.12285233e+00,
        8.37048292e-01, -2.14226651e+00,  8.14002395e-01,  5.20106912e-01,
        2.93652844e+00,  5.85487938e+00,  1.38601363e-01, -8.26935291e-01,
        4.92203379e+00,  3.32286358e+00,  5.75343657e+00,  3.62685442e+00,
        4.26375818e+00, -6.69878960e+00,  8.92031574e+00,  3.02105832e+00,
        5.05395508e+00,  1.55117023e+00,  2.0307717