In [41]:
import os 
import codecs
import numpy as np
from tensorflow import keras
from keras_bert import load_trained_model_from_checkpoint, Tokenizer

In [9]:
os.environ['TF_KERAS'] = '1'

In [11]:
config_path = 'bert_checkpoint/bert_config.json'
checkpoint_path = 'bert_checkpoint/bert_model.ckpt'
vocab_path = 'bert_checkpoint/vocab.txt'

In [14]:
token_dict = {}

with codecs.open(vocab_path, 'r', 'utf-8') as reader:
    for line in reader:
        token = line.strip()
        token_dict[token] = len(token_dict)

In [18]:
bert_model = load_trained_model_from_checkpoint(config_path, checkpoint_path, seq_len=None)

In [20]:
bert_model.summary(line_length=120)

 None, 768)          1536          Encoder-3-FeedForward-Add[0][0]         
________________________________________________________________________________________________________________________
Encoder-4-MultiHeadSelfAttention (Mult (None, None, 768)          2362368       Encoder-3-FeedForward-Norm[0][0]        
________________________________________________________________________________________________________________________
Encoder-4-MultiHeadSelfAttention-Dropo (None, None, 768)          0             Encoder-4-MultiHeadSelfAttention[0][0]  
________________________________________________________________________________________________________________________
Encoder-4-MultiHeadSelfAttention-Add ( (None, None, 768)          0             Encoder-3-FeedForward-Norm[0][0]        
                                                                                Encoder-4-MultiHeadSelfAttention-Dropout
_____________________________________________________________________________

In [21]:
tokenizer = Tokenizer(token_dict)

In [22]:
tokenizer

In [23]:
text = '语言模型'

In [25]:
indices, segments = tokenizer.encode(first=text, max_len=512)

In [27]:
indices[:10]

[101, 6427, 6241, 3563, 1798, 102, 0, 0, 0, 0]

In [28]:
segments[:10]

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

In [30]:
predicts = bert_model.predict([np.array([indices]), np.array([segments])])

In [31]:
predicts

array([[[-0.6325099 ,  0.2030244 ,  0.07936614, ...,  0.49122632,
         -0.20493308,  0.25752574],
        [-0.75883555,  0.09651931,  1.0718751 , ..., -0.6109692 ,
          0.04312191,  0.03881435],
        [ 0.54770267, -0.7921164 ,  0.44435146, ...,  0.4244931 ,
          0.4110575 ,  0.08222896],
        ...,
        [-0.45575452, -0.1718734 , -0.19931796, ...,  0.10876012,
         -0.19919592, -0.05005006],
        [-0.4851753 ,  0.04089726, -0.46500114, ...,  0.27471033,
         -0.10994234,  0.06527417],
        [-0.47847873, -0.36442548, -0.37093288, ...,  0.4559859 ,
          0.03942422,  0.17148809]]], dtype=float32)

In [33]:
predicts.shape

(1, 512, 768)

In [34]:
predicts[0]

array([[-0.6325099 ,  0.2030244 ,  0.07936614, ...,  0.49122632,
        -0.20493308,  0.25752574],
       [-0.75883555,  0.09651931,  1.0718751 , ..., -0.6109692 ,
         0.04312191,  0.03881435],
       [ 0.54770267, -0.7921164 ,  0.44435146, ...,  0.4244931 ,
         0.4110575 ,  0.08222896],
       ...,
       [-0.45575452, -0.1718734 , -0.19931796, ...,  0.10876012,
        -0.19919592, -0.05005006],
       [-0.4851753 ,  0.04089726, -0.46500114, ...,  0.27471033,
        -0.10994234,  0.06527417],
       [-0.47847873, -0.36442548, -0.37093288, ...,  0.4559859 ,
         0.03942422,  0.17148809]], dtype=float32)

In [35]:
predicts[0].shape

(512, 768)

In [36]:
predicts[0][:5]

array([[-0.6325099 ,  0.2030244 ,  0.07936614, ...,  0.49122632,
        -0.20493308,  0.25752574],
       [-0.75883555,  0.09651931,  1.0718751 , ..., -0.6109692 ,
         0.04312191,  0.03881435],
       [ 0.54770267, -0.7921164 ,  0.44435146, ...,  0.4244931 ,
         0.4110575 ,  0.08222896],
       [-0.29242367,  0.60527146,  0.4996855 , ...,  0.86041474,
        -0.6533172 ,  0.5369072 ],
       [-0.74734503,  0.49431655,  0.7185168 , ...,  0.3848617 ,
        -0.74090546,  0.39056852]], dtype=float32)

In [39]:
a = keras.layers.Lambda(lambda predicts: predicts[:, 0])(predicts)

In [42]:
a.shape 

TensorShape([1, 768])

In [43]:
predicts.shape 

(1, 512, 768)

In [44]:
predicts[:, 0].shape

(1, 768)