In [1]:
import numpy as np 
import tensorflow as tf 
import tensorflow_datasets as tfds 

print(tf.__version__)

2.1.0


In [2]:
TRAIN_DATA_URL = "https://storage.googleapis.com/tf-datasets/titanic/train.csv"
TEST_DATA_URL = "https://storage.googleapis.com/tf-datasets/titanic/eval.csv"

train_file_path = tf.keras.utils.get_file("train.csv", TRAIN_DATA_URL)
test_file_path = tf.keras.utils.get_file("eval.csv", TEST_DATA_URL)

16384/13049 [=====================================] - 0s 26us/step


In [3]:
train_file_path

'/home/mark/.keras/datasets/train.csv'

In [4]:
np.set_printoptions(precision=3, suppress=True)

In [5]:
!head {train_file_path}

survived,sex,age,n_siblings_spouses,parch,fare,class,deck,embark_town,alone
0,male,22.0,1,0,7.25,Third,unknown,Southampton,n
1,female,38.0,1,0,71.2833,First,C,Cherbourg,n
1,female,26.0,0,0,7.925,Third,unknown,Southampton,y
1,female,35.0,1,0,53.1,First,C,Southampton,n
0,male,28.0,0,0,8.4583,Third,unknown,Queenstown,y
0,male,2.0,3,1,21.075,Third,unknown,Southampton,n
1,female,27.0,0,2,11.1333,Third,unknown,Southampton,n
1,female,14.0,1,0,30.0708,Second,unknown,Cherbourg,n
1,female,4.0,1,1,16.7,Third,G,Southampton,n


In [6]:
LABEL_COLUME = 'survived'
LABELS = [0, 1]

In [8]:
def get_dataset(file_path):
    dataset = tf.data.experimental.make_csv_dataset(
        file_path,
        batch_size=12,
        label_name=LABEL_COLUME,
        na_value="?",
        num_epochs=1,
        ignore_errors=True
    )
    return dataset

In [9]:
raw_train_data = get_dataset(train_file_path)
raw_train_data

<PrefetchDataset shapes: (OrderedDict([(sex, (None,)), (age, (None,)), (n_siblings_spouses, (None,)), (parch, (None,)), (fare, (None,)), (class, (None,)), (deck, (None,)), (embark_town, (None,)), (alone, (None,))]), (None,)), types: (OrderedDict([(sex, tf.string), (age, tf.float32), (n_siblings_spouses, tf.int32), (parch, tf.int32), (fare, tf.float32), (class, tf.string), (deck, tf.string), (embark_town, tf.string), (alone, tf.string)]), tf.int32)>

In [10]:
raw_test_data = get_dataset(test_file_path)

In [11]:
examples, labels = next(iter(raw_train_data))

In [12]:
examples

OrderedDict([('sex',
              <tf.Tensor: shape=(12,), dtype=string, numpy=
              array([b'male', b'male', b'male', b'male', b'male', b'male', b'male',
                     b'female', b'male', b'male', b'male', b'female'], dtype=object)>),
             ('age',
              <tf.Tensor: shape=(12,), dtype=float32, numpy=
              array([29., 41., 28., 26., 28.,  4., 28., 28., 34., 28., 28., 25.],
                    dtype=float32)>),
             ('n_siblings_spouses',
              <tf.Tensor: shape=(12,), dtype=int32, numpy=array([0, 2, 0, 0, 0, 4, 0, 0, 0, 0, 1, 1], dtype=int32)>),
             ('parch',
              <tf.Tensor: shape=(12,), dtype=int32, numpy=array([0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0], dtype=int32)>),
             ('fare',
              <tf.Tensor: shape=(12,), dtype=float32, numpy=
              array([ 7.896, 14.108, 52.   ,  7.887,  7.775, 31.275,  7.229,  7.879,
                     26.55 , 29.7  ,  7.75 ,  7.925], dtype=float32)>),
          

In [ ]:
labels