In [2]:
import tensorflow as tf 
import numpy  as np 
import os 
import time 

In [3]:
path_to_file = tf.keras.utils.get_file('shakespeare.txt', 'https://storage.googleapis.com/download.tensorflow.org/data/shakespeare.txt')


In [4]:
path_to_file

'/home/mark/.keras/datasets/shakespeare.txt'

In [5]:
text = open(path_to_file, 'rb').read().decode(encoding='utf-8')

In [6]:
len(text)

1115394

In [7]:
text[:250]

'First Citizen:\nBefore we proceed any further, hear me speak.\n\nAll:\nSpeak, speak.\n\nFirst Citizen:\nYou are all resolved rather to die than to famish?\n\nAll:\nResolved. resolved.\n\nFirst Citizen:\nFirst, you know Caius Marcius is chief enemy to the people.\n'

In [8]:
vocab = sorted(set(text))

In [9]:
vocab

['\n',
 ' ',
 '!',
 '$',
 '&',
 "'",
 ',',
 '-',
 '.',
 '3',
 ':',
 ';',
 '?',
 'A',
 'B',
 'C',
 'D',
 'E',
 'F',
 'G',
 'H',
 'I',
 'J',
 'K',
 'L',
 'M',
 'N',
 'O',
 'P',
 'Q',
 'R',
 'S',
 'T',
 'U',
 'V',
 'W',
 'X',
 'Y',
 'Z',
 'a',
 'b',
 'c',
 'd',
 'e',
 'f',
 'g',
 'h',
 'i',
 'j',
 'k',
 'l',
 'm',
 'n',
 'o',
 'p',
 'q',
 'r',
 's',
 't',
 'u',
 'v',
 'w',
 'x',
 'y',
 'z']

In [10]:
len(vocab)

65

In [11]:
char2idx = {u: i for i, u in enumerate(vocab)}

In [12]:
char2idx

{'\n': 0,
 ' ': 1,
 '!': 2,
 '$': 3,
 '&': 4,
 "'": 5,
 ',': 6,
 '-': 7,
 '.': 8,
 '3': 9,
 ':': 10,
 ';': 11,
 '?': 12,
 'A': 13,
 'B': 14,
 'C': 15,
 'D': 16,
 'E': 17,
 'F': 18,
 'G': 19,
 'H': 20,
 'I': 21,
 'J': 22,
 'K': 23,
 'L': 24,
 'M': 25,
 'N': 26,
 'O': 27,
 'P': 28,
 'Q': 29,
 'R': 30,
 'S': 31,
 'T': 32,
 'U': 33,
 'V': 34,
 'W': 35,
 'X': 36,
 'Y': 37,
 'Z': 38,
 'a': 39,
 'b': 40,
 'c': 41,
 'd': 42,
 'e': 43,
 'f': 44,
 'g': 45,
 'h': 46,
 'i': 47,
 'j': 48,
 'k': 49,
 'l': 50,
 'm': 51,
 'n': 52,
 'o': 53,
 'p': 54,
 'q': 55,
 'r': 56,
 's': 57,
 't': 58,
 'u': 59,
 'v': 60,
 'w': 61,
 'x': 62,
 'y': 63,
 'z': 64}

In [13]:
idx2char = np.array(vocab)

In [14]:
idx2char

array(['\n', ' ', '!', '$', '&', "'", ',', '-', '.', '3', ':', ';', '?',
       'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M',
       'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z',
       'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm',
       'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z'],
      dtype='<U1')

In [15]:
repr(idx2char)

'array([\'\\n\', \' \', \'!\', \'$\', \'&\', "\'", \',\', \'-\', \'.\', \'3\', \':\', \';\', \'?\',\n       \'A\', \'B\', \'C\', \'D\', \'E\', \'F\', \'G\', \'H\', \'I\', \'J\', \'K\', \'L\', \'M\',\n       \'N\', \'O\', \'P\', \'Q\', \'R\', \'S\', \'T\', \'U\', \'V\', \'W\', \'X\', \'Y\', \'Z\',\n       \'a\', \'b\', \'c\', \'d\', \'e\', \'f\', \'g\', \'h\', \'i\', \'j\', \'k\', \'l\', \'m\',\n       \'n\', \'o\', \'p\', \'q\', \'r\', \'s\', \'t\', \'u\', \'v\', \'w\', \'x\', \'y\', \'z\'],\n      dtype=\'<U1\')'

In [16]:
repr(char2idx)

'{\'\\n\': 0, \' \': 1, \'!\': 2, \'$\': 3, \'&\': 4, "\'": 5, \',\': 6, \'-\': 7, \'.\': 8, \'3\': 9, \':\': 10, \';\': 11, \'?\': 12, \'A\': 13, \'B\': 14, \'C\': 15, \'D\': 16, \'E\': 17, \'F\': 18, \'G\': 19, \'H\': 20, \'I\': 21, \'J\': 22, \'K\': 23, \'L\': 24, \'M\': 25, \'N\': 26, \'O\': 27, \'P\': 28, \'Q\': 29, \'R\': 30, \'S\': 31, \'T\': 32, \'U\': 33, \'V\': 34, \'W\': 35, \'X\': 36, \'Y\': 37, \'Z\': 38, \'a\': 39, \'b\': 40, \'c\': 41, \'d\': 42, \'e\': 43, \'f\': 44, \'g\': 45, \'h\': 46, \'i\': 47, \'j\': 48, \'k\': 49, \'l\': 50, \'m\': 51, \'n\': 52, \'o\': 53, \'p\': 54, \'q\': 55, \'r\': 56, \'s\': 57, \'t\': 58, \'u\': 59, \'v\': 60, \'w\': 61, \'x\': 62, \'y\': 63, \'z\': 64}'

In [17]:
text_as_int = np.array([char2idx[c] for c in text])

In [18]:
text_as_int

array([18, 47, 56, ..., 45,  8,  0])

In [19]:
text_as_int.shape

(1115394,)

In [20]:
print ('{} ---- characters mapped to int ---- > {}'.format(repr(text[:13]), text_as_int[:13]))


'First Citizen' ---- characters mapped to int ---- > [18 47 56 57 58  1 15 47 58 47 64 43 52]


In [21]:
seq_length = 100
example_per_epoch = len(text)

In [22]:
example_per_epoch

1115394

In [23]:
char_dataset = tf.data.Dataset.from_tensor_slices(text_as_int)

In [24]:
char_dataset

<TensorSliceDataset shapes: (), types: tf.int64>

In [25]:
for i in char_dataset.take(5):
    print(idx2char[i.numpy()])

F
i
r
s
t


In [26]:
sequences = char_dataset.batch(seq_length+1, drop_remainder=True)

In [27]:
for item in sequences.take(5):
    print(repr(''.join(idx2char[item.numpy()])))

'First Citizen:\nBefore we proceed any further, hear me speak.\n\nAll:\nSpeak, speak.\n\nFirst Citizen:\nYou '
'are all resolved rather to die than to famish?\n\nAll:\nResolved. resolved.\n\nFirst Citizen:\nFirst, you k'
"now Caius Marcius is chief enemy to the people.\n\nAll:\nWe know't, we know't.\n\nFirst Citizen:\nLet us ki"
"ll him, and we'll have corn at our own price.\nIs't a verdict?\n\nAll:\nNo more talking on't; let it be d"
'one: away, away!\n\nSecond Citizen:\nOne word, good citizens.\n\nFirst Citizen:\nWe are accounted poor citi'


In [28]:
for item in sequences.take(5):
    print(''.join(idx2char[item.numpy()]))

First Citizen:
Before we proceed any further, hear me speak.

All:
Speak, speak.

First Citizen:
You 
are all resolved rather to die than to famish?

All:
Resolved. resolved.

First Citizen:
First, you k
now Caius Marcius is chief enemy to the people.

All:
We know't, we know't.

First Citizen:
Let us ki
ll him, and we'll have corn at our own price.
Is't a verdict?

All:
No more talking on't; let it be d
one: away, away!

Second Citizen:
One word, good citizens.

First Citizen:
We are accounted poor citi


In [29]:
def split_input_target(chunk):
    input_text = chunk[:-1]
    target_text = chunk[1:]
    return input_text, target_text

In [30]:
dataset = sequences.map(split_input_target)

In [31]:
dataset

<MapDataset shapes: ((100,), (100,)), types: (tf.int64, tf.int64)>

In [32]:
dataset.take(1)

<TakeDataset shapes: ((100,), (100,)), types: (tf.int64, tf.int64)>

In [33]:
for input_example, target_example in dataset.take(1):
    print(input_example)
    print(target_example)
    break

tf.Tensor(
[18 47 56 57 58  1 15 47 58 47 64 43 52 10  0 14 43 44 53 56 43  1 61 43
  1 54 56 53 41 43 43 42  1 39 52 63  1 44 59 56 58 46 43 56  6  1 46 43
 39 56  1 51 43  1 57 54 43 39 49  8  0  0 13 50 50 10  0 31 54 43 39 49
  6  1 57 54 43 39 49  8  0  0 18 47 56 57 58  1 15 47 58 47 64 43 52 10
  0 37 53 59], shape=(100,), dtype=int64)
tf.Tensor(
[47 56 57 58  1 15 47 58 47 64 43 52 10  0 14 43 44 53 56 43  1 61 43  1
 54 56 53 41 43 43 42  1 39 52 63  1 44 59 56 58 46 43 56  6  1 46 43 39
 56  1 51 43  1 57 54 43 39 49  8  0  0 13 50 50 10  0 31 54 43 39 49  6
  1 57 54 43 39 49  8  0  0 18 47 56 57 58  1 15 47 58 47 64 43 52 10  0
 37 53 59  1], shape=(100,), dtype=int64)


In [34]:
BATCH_SIZE = 64

BUFFER_SIZE = 10000

dataset = dataset.shuffle(BUFFER_SIZE).batch(BATCH_SIZE, drop_remainder=True)

In [35]:
dataset

<BatchDataset shapes: ((64, 100), (64, 100)), types: (tf.int64, tf.int64)>

In [36]:
vocab_size = len(vocab)

In [37]:
vocab_size

65

In [38]:
embedding_dim = 256

In [39]:
rnn_units = 1024

In [40]:
def build_model(vocab_size, embedding_dim, rnn_units, batch_size):
    model = tf.keras.Sequential([
        tf.keras.layers.Embedding(vocab_size, embedding_dim, batch_input_shape=[batch_size, None]),
        tf.keras.layers.GRU(rnn_units, return_sequences=True, stateful=True, recurrent_initializer='glorot_uniform'),
        tf.keras.layers.Dense(vocab_size)
    ])

    return model

In [41]:
model = build_model(
    vocab_size=len(vocab),
    embedding_dim=embedding_dim,
    rnn_units=rnn_units,
    batch_size=BATCH_SIZE
)

In [42]:
model

In [43]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding (Embedding)        (64, None, 256)           16640     
_________________________________________________________________
gru (GRU)                    (64, None, 1024)          3938304   
_________________________________________________________________
dense (Dense)                (64, None, 65)            66625     
Total params: 4,021,569
Trainable params: 4,021,569
Non-trainable params: 0
_________________________________________________________________


In [44]:
for input_example_batch, target_emample_batch in dataset.take(1):
    example_batch_predictions = model(input_example_batch)
    print(example_batch_predictions.shape)

(64, 100, 65)


In [45]:
sampled_indices = tf.random.categorical(
    example_batch_predictions[0],
    num_samples=1
)

In [46]:
sampled_indices

<tf.Tensor: shape=(100, 1), dtype=int64, numpy=
array([[17],
       [16],
       [43],
       [13],
       [22],
       [23],
       [ 0],
       [18],
       [54],
       [ 8],
       [45],
       [53],
       [32],
       [29],
       [56],
       [13],
       [46],
       [21],
       [48],
       [13],
       [55],
       [51],
       [29],
       [23],
       [ 9],
       [42],
       [26],
       [ 2],
       [26],
       [59],
       [40],
       [52],
       [42],
       [47],
       [45],
       [42],
       [58],
       [23],
       [40],
       [50],
       [ 8],
       [18],
       [10],
       [27],
       [ 1],
       [37],
       [21],
       [11],
       [12],
       [28],
       [12],
       [49],
       [62],
       [36],
       [39],
       [57],
       [ 8],
       [53],
       [21],
       [31],
       [39],
       [35],
       [29],
       [54],
       [ 6],
       [17],
       [57],
       [ 7],
       [46],
       [26],
       [37],
       [34],
       [10],
   

In [51]:
sampled_indices = tf.squeeze(sampled_indices, axis=-1).numpy()

InvalidArgumentError: Can not squeeze dim[0], expected a dimension of 1, got 100 [Op:Squeeze]

In [52]:
sampled_indices

array([17, 16, 43, 13, 22, 23,  0, 18, 54,  8, 45, 53, 32, 29, 56, 13, 46,
       21, 48, 13, 55, 51, 29, 23,  9, 42, 26,  2, 26, 59, 40, 52, 42, 47,
       45, 42, 58, 23, 40, 50,  8, 18, 10, 27,  1, 37, 21, 11, 12, 28, 12,
       49, 62, 36, 39, 57,  8, 53, 21, 31, 39, 35, 29, 54,  6, 17, 57,  7,
       46, 26, 37, 34, 10,  7, 51, 52, 18, 11, 17, 49, 26, 13, 59,  1,  2,
       57, 23, 48, 15, 33, 34, 53, 29, 59,  0, 57, 10, 41, 56, 45])

In [54]:
len(sampled_indices)

100

In [55]:
sampled_indices.size

100

In [56]:
example_batch_predictions[0]

<tf.Tensor: shape=(100, 65), dtype=float32, numpy=
array([[ 0.00710559, -0.005002  , -0.00750123, ..., -0.00295031,
         0.00869691, -0.01179926],
       [ 0.01340519, -0.01506648, -0.00388819, ...,  0.00298745,
        -0.0074836 , -0.00965445],
       [ 0.00268888, -0.00645789, -0.00336343, ..., -0.01327759,
        -0.00390074,  0.01017858],
       ...,
       [-0.0063599 ,  0.0030371 , -0.00205557, ..., -0.00588686,
        -0.00663852, -0.00243716],
       [ 0.00539532,  0.0078963 , -0.00354857, ..., -0.00683352,
        -0.00027729, -0.00015959],
       [-0.00102552,  0.01246046, -0.0013303 , ..., -0.00717567,
        -0.00781539, -0.00598164]], dtype=float32)>

In [57]:
def loss(labels, logits):
    return tf.keras.losses.sparse_categorical_crossentropy(labels, logits, from_logits=True)

In [58]:
example_batch_loss = loss(target_emample_batch, example_batch_predictions)

In [59]:
example_batch_predictions.shape

TensorShape([64, 100, 65])

In [61]:
example_batch_loss.numpy().size

6400

In [63]:
example_batch_loss.shape

TensorShape([64, 100])

In [64]:
model.compile(optimizer='adam', loss=loss)

In [67]:
checkpoint_dir = './training_checkpoints_2'

checkpoint_prefix = os.path.join(checkpoint_dir, "ckpt_{epoch}")

checkpoint_callback = tf.keras.callbacks.ModelCheckpoint(
    filepath=checkpoint_prefix,
    save_weights_only=True
)

In [72]:
EPOCHS = 30

In [73]:
history = model.fit(
    dataset,
    epochs=EPOCHS, 
    callbacks=[checkpoint_callback]
)

Train for 172 steps
Epoch 1/30
172/172 [==============================] - 135s 784ms/step - loss: 0.8748
Epoch 2/30
172/172 [==============================] - 135s 787ms/step - loss: 0.8474
Epoch 3/30
172/172 [==============================] - 135s 785ms/step - loss: 0.8213
Epoch 4/30
172/172 [==============================] - 135s 785ms/step - loss: 0.7961
Epoch 5/30
172/172 [==============================] - 135s 784ms/step - loss: 0.7739
Epoch 6/30
172/172 [==============================] - 135s 784ms/step - loss: 0.7560
Epoch 7/30
172/172 [==============================] - 135s 785ms/step - loss: 0.7387
Epoch 8/30
172/172 [==============================] - 135s 785ms/step - loss: 0.7220
Epoch 9/30
172/172 [==============================] - 135s 786ms/step - loss: 0.7114
Epoch 10/30
172/172 [==============================] - 136s 789ms/step - loss: 0.7023
Epoch 11/30
172/172 [==============================] - 135s 784ms/step - loss: 0.6912
Epoch 12/30
172/172 [======================

In [74]:
tf.train.latest_checkpoint(checkpoint_dir)

'./training_checkpoints_2/ckpt_30'

In [80]:
model = build_model(vocab_size, embedding_dim, rnn_units, batch_size=1)

In [81]:
model.load_weights(tf.train.latest_checkpoint(checkpoint_dir))

In [82]:
model.build(tf.TensorShape([1, None]))

In [83]:
model.summary()

Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_2 (Embedding)      (1, None, 256)            16640     
_________________________________________________________________
gru_2 (GRU)                  (1, None, 1024)           3938304   
_________________________________________________________________
dense_2 (Dense)              (1, None, 65)             66625     
Total params: 4,021,569
Trainable params: 4,021,569
Non-trainable params: 0
_________________________________________________________________


In [89]:
start_string=u"ROMEO: "

In [90]:
num_generate = 1000

In [119]:
input_eval = [char2idx[s] for s in start_string]

In [120]:
input_eval

[30, 27, 25, 17, 27, 10, 1]

In [121]:
input_eval = tf.expand_dims(input_eval, 0)

In [122]:
input_eval.shape

TensorShape([1, 7])

In [123]:
text_generated = []
temperature = 1.0

In [124]:
model.reset_states()

In [125]:
predictions = model(input_eval)
predictions.shape

TensorShape([1, 7, 65])

In [126]:
predictions = tf.squeeze(predictions, 0)

In [127]:
predictions.shape

TensorShape([7, 65])

In [131]:
predicted_id = tf.random.categorical(predictions, num_samples=1)[-1,0].numpy()

In [132]:
predicted_id

34

In [133]:
input_eval = tf.expand_dims([predicted_id], 0)

In [134]:
input_eval

<tf.Tensor: shape=(1, 1), dtype=int32, numpy=array([[34]], dtype=int32)>

In [135]:
input_eval.numpy()

array([[34]], dtype=int32)

In [136]:
model = build_model(
    vocab_size=len(vocab),
    embedding_dim=embedding_dim,
    rnn_units=rnn_units,
    batch_size=BATCH_SIZE
)

In [137]:
optimizer = tf.keras.optimizers.Adam()

In [138]:
@tf.function
def train_step(inp, target):
    with tf.GradientTape() as tape:
        predictions = model(inp)
        loss = tf.reduce_mean(tf.keras.losses.sparse_categorical_crossentropy(target, predictions, from_logits=True))
        grads = tape.gradient(loss, model.trainable_variables)
        optimizer.apply_gradients(zip(grads, model.trainable_variables))
    return loss

In [140]:
EPOCHS = 10

for epoch in range(EPOCHS):
    start = time.time()

    hidden = model.reset_states()
    for batch_n, (inp, target) in enumerate(dataset):
        loss = train_step(inp, target)

        if batch_n % 100 == 0:
            template = 'Epoch {} Batch {} Loss {}'
            print(template.format(epoch+1, batch_n, loss))
    if (epoch + 1) % 5 == 0:
        model.save_weights(checkpoint_prefix.format(epoch=epoch))
    print ('Epoch {} Loss {:.4f}'.format(epoch+1, loss))
    print ('Time taken for 1 epoch {} sec\n'.format(time.time() - start))

model.save_weights(checkpoint_prefix.format(epoch=epoch))

Epoch 1 Batch 0 Loss 4.1736907958984375
Epoch 1 Batch 100 Loss 2.3560678958892822
Epoch 1 Loss 2.1229
Time taken for 1 epoch 135.5267014503479 sec

Epoch 2 Batch 0 Loss 2.1642160415649414
Epoch 2 Batch 100 Loss 1.9267539978027344
Epoch 2 Loss 1.7885
Time taken for 1 epoch 134.8104853630066 sec

Epoch 3 Batch 0 Loss 1.7800774574279785
Epoch 3 Batch 100 Loss 1.6917648315429688
Epoch 3 Loss 1.5802
Time taken for 1 epoch 134.68054151535034 sec

Epoch 4 Batch 0 Loss 1.5242564678192139
Epoch 4 Batch 100 Loss 1.5288411378860474
Epoch 4 Loss 1.5434
Time taken for 1 epoch 134.89468455314636 sec

Epoch 5 Batch 0 Loss 1.4983221292495728
Epoch 5 Batch 100 Loss 1.4548025131225586
Epoch 5 Loss 1.4638
Time taken for 1 epoch 134.9898340702057 sec

Epoch 6 Batch 0 Loss 1.3885425329208374
Epoch 6 Batch 100 Loss 1.3822537660598755
Epoch 6 Loss 1.4191
Time taken for 1 epoch 135.08123302459717 sec

Epoch 7 Batch 0 Loss 1.3368542194366455
Epoch 7 Batch 100 Loss 1.3446301221847534
Epoch 7 Loss 1.3466
Time ta