In [1]:
import tensorflow as tf

a = tf.constant([[1,2,3],[4,5,6]])
b = tf.constant([[7,8,9],[0,1,7]])
c = tf.stack([a, b], axis = 0)

In [12]:
a

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)>

In [13]:
b

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[7, 8, 9],
       [0, 1, 7]], dtype=int32)>

In [2]:
tf.concat([a, b], axis=0)

<tf.Tensor: shape=(4, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [0, 1, 7]], dtype=int32)>

In [3]:
tf.concat([a, b], axis=1)

<tf.Tensor: shape=(2, 6), dtype=int32, numpy=
array([[1, 2, 3, 7, 8, 9],
       [4, 5, 6, 0, 1, 7]], dtype=int32)>

In [14]:
c

<tf.Tensor: shape=(2, 2, 3), dtype=int32, numpy=
array([[[1, 2, 3],
        [4, 5, 6]],

       [[7, 8, 9],
        [0, 1, 7]]], dtype=int32)>

In [15]:
c[0]

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)>

In [16]:
c[1]

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[7, 8, 9],
       [0, 1, 7]], dtype=int32)>

In [17]:
d = tf.stack([a, b], axis=1)

In [19]:
d

<tf.Tensor: shape=(2, 2, 3), dtype=int32, numpy=
array([[[1, 2, 3],
        [7, 8, 9]],

       [[4, 5, 6],
        [0, 1, 7]]], dtype=int32)>

In [18]:
d[0]

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [7, 8, 9]], dtype=int32)>