In [15]:
import tensorflow as tf 
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing import sequence

In [16]:
text1 = "学习keras的Tokenizer"
text2 = "就是这么的简单"
texts = [text1, text2]

In [17]:
tokenizer = Tokenizer(num_words=5000, char_level=True, oov_token='UNK')

In [18]:
tokenizer

In [19]:
tokenizer.fit_on_texts(texts)

In [20]:
tokenizer.word_counts

OrderedDict([('学', 1),
             ('习', 1),
             ('k', 2),
             ('e', 3),
             ('r', 2),
             ('a', 1),
             ('s', 1),
             ('的', 2),
             ('t', 1),
             ('o', 1),
             ('n', 1),
             ('i', 1),
             ('z', 1),
             ('就', 1),
             ('是', 1),
             ('这', 1),
             ('么', 1),
             ('简', 1),
             ('单', 1)])

In [21]:
tokenizer.word_docs

defaultdict(int,
            {'e': 1,
             's': 1,
             't': 1,
             'i': 1,
             '习': 1,
             '学': 1,
             'z': 1,
             'a': 1,
             'k': 1,
             'r': 1,
             '的': 2,
             'n': 1,
             'o': 1,
             '简': 1,
             '这': 1,
             '是': 1,
             '单': 1,
             '就': 1,
             '么': 1})

In [22]:
tokenizer.document_count

2

In [23]:
tokenizer.word_index

{'UNK': 1,
 'e': 2,
 'k': 3,
 'r': 4,
 '的': 5,
 '学': 6,
 '习': 7,
 'a': 8,
 's': 9,
 't': 10,
 'o': 11,
 'n': 12,
 'i': 13,
 'z': 14,
 '就': 15,
 '是': 16,
 '这': 17,
 '么': 18,
 '简': 19,
 '单': 20}

In [24]:
s = tokenizer.texts_to_matrix(texts)

In [25]:
s

array([[0., 0., 1., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [26]:
s[0]

array([0., 0., 1., ..., 0., 0., 0.])

In [27]:
for i in s[0]:
    print(i)

0.0
0.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0


In [28]:
tokenizer.texts_to_matrix(texts).shape

(2, 5000)

In [29]:
tokenizer.texts_to_sequences(texts)

[[6, 7, 3, 2, 4, 8, 9, 5, 10, 11, 3, 2, 12, 13, 14, 2, 4],
 [15, 16, 17, 18, 5, 19, 20]]

In [30]:
tokenizer.texts_to_sequences(text1)

[[6],
 [7],
 [3],
 [2],
 [4],
 [8],
 [9],
 [5],
 [10],
 [11],
 [3],
 [2],
 [12],
 [13],
 [14],
 [2],
 [4]]

In [31]:
text = tokenizer.texts_to_sequences(texts)

In [51]:
text

[[6, 7, 3, 2, 4, 8, 9, 5, 10, 11, 3, 2, 12, 13, 14, 2, 4],
 [15, 16, 17, 18, 5, 19, 20]]

In [32]:
texts

['学习keras的Tokenizer', '就是这么的简单']

In [33]:
sequence.pad_sequences(text, maxlen=30, padding='post',truncating='post')

array([[ 6,  7,  3,  2,  4,  8,  9,  5, 10, 11,  3,  2, 12, 13, 14,  2,
         4,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [15, 16, 17, 18,  5, 19, 20,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0]],
      dtype=int32)

In [34]:
sequence.pad_sequences(text, maxlen=30, padding='pre',truncating='pre')

array([[ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  6,  7,  3,
         2,  4,  8,  9,  5, 10, 11,  3,  2, 12, 13, 14,  2,  4],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0, 15, 16, 17, 18,  5, 19, 20]],
      dtype=int32)

In [35]:
tokenizer.texts_to_matrix(texts)

array([[0., 0., 1., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [36]:
tokenizer.texts_to_matrix(texts).shape

(2, 5000)

In [37]:
import numpy as np

In [38]:
a = np.array([
    [1, 2, 3]
])

In [39]:
a.size

3

In [40]:
b = np.array([
    [4, 5, 6],
    [7, 8, 9]
])

In [41]:
b.shape

(2, 3)

In [42]:
c = a + b

In [43]:
c

array([[ 5,  7,  9],
       [ 8, 10, 12]])

In [45]:
tf.keras.preprocessing.text.text_to_word_sequence(text1,
                                               filters='!"#$%&()*+,-./:;<=>?@[\]^_`{|}~\t\n',
                                               lower=True,
                                               split="")

['学习keras的tokenizer']

In [50]:
tf.keras.preprocessing.text.one_hot(text1,
                                 5000,
                                 filters='!"#$%&()*+,-./:;<=>?@[\]^_`{|}~\t\n',
                                 lower=True)

[3190]